/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.dial.pelanggan;

import java.awt.Color;
import java.sql.SQLException;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JDialog {
private util.Db d;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal,util.Db db) {
        super(parent, modal);
        d=db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kecAlmt = new javax.swing.JTextField();
        kabAlmt = new javax.swing.JTextField();
        provAlmt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desAlmt = new javax.swing.JTextArea();
        nm = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telp = new javax.swing.JTextField();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dialog Penambah Pelanggan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Desa");

        jLabel4.setText("Kecamatan");

        jLabel5.setText("Kota");

        jLabel6.setText("Provinsi");

        kecAlmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kecAlmtKeyReleased(evt);
            }
        });

        kabAlmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kabAlmtKeyReleased(evt);
            }
        });

        provAlmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                provAlmtKeyReleased(evt);
            }
        });

        desAlmt.setColumns(20);
        desAlmt.setRows(5);
        desAlmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                desAlmtKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(desAlmt);

        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmKeyReleased(evt);
            }
        });

        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodeKeyReleased(evt);
            }
        });

        jLabel7.setText("Telpon");

        telp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telpKeyReleased(evt);
            }
        });

        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/sd-card.png"))); // NOI18N
        s.setText("SIMPAN");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(provAlmt)
                            .addComponent(kabAlmt)
                            .addComponent(kecAlmt)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(nm)
                            .addComponent(kode)
                            .addComponent(telp))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(s, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kecAlmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kabAlmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provAlmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        javax.swing.JOptionPane.showMessageDialog(rootPane, "Nothing to do");
    }//GEN-LAST:event_formWindowClosing

    private void kodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyReleased
    if(!kode.getText().isEmpty())try {
        java.sql.PreparedStatement p=d.getPS("select (kode=?)as oke from pelanggan");
        p.setString(1, kode.getText());
        java.sql.ResultSet r=p.executeQuery();
        if(r.next()){
            if(r.getBoolean("oke"))kode.setForeground(Color.red);
            else kode.setForeground(Color.BLACK);
        }r.close();
        p.close();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }refresh();
    }//GEN-LAST:event_kodeKeyReleased

    private void desAlmtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desAlmtKeyReleased
        refresh();
    }//GEN-LAST:event_desAlmtKeyReleased

    private void kecAlmtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kecAlmtKeyReleased
        refresh();
    }//GEN-LAST:event_kecAlmtKeyReleased

    private void kabAlmtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kabAlmtKeyReleased
        refresh();
    }//GEN-LAST:event_kabAlmtKeyReleased

    private void provAlmtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_provAlmtKeyReleased
        refresh();
    }//GEN-LAST:event_provAlmtKeyReleased

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));try {
        new entity.dao.DAOPelanggan(d).insert(new entity.Pelanggan(kode.getText(), nm.getText(), getAlmt(), telp.getText()));
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }this.setVisible(false);
    }//GEN-LAST:event_sActionPerformed

    private void nmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyReleased
        refresh();
    }//GEN-LAST:event_nmKeyReleased

    private void telpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telpKeyReleased
        refresh();
    }//GEN-LAST:event_telpKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea desAlmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kabAlmt;
    private javax.swing.JTextField kecAlmt;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField provAlmt;
    private javax.swing.JButton s;
    private javax.swing.JTextField telp;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        s.setEnabled(isAlmt()&&!kode.getText().isEmpty()&&Color.BLACK==kode.getForeground()&&!nm.getText().isEmpty()&&!telp.getText().isEmpty());
    }

    private boolean isAlmt() {
        boolean b=!desAlmt.getText().isEmpty();
        b|=!kabAlmt.getText().isEmpty();
        b|=!kecAlmt.getText().isEmpty();
        b|=!provAlmt.getText().isEmpty();
        return b;
    }

    private String getAlmt() {
        return desAlmt.getText()+", "+kecAlmt.getText()+", "+kabAlmt.getText()+", "+provAlmt.getText();
    }
}
