/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.dial.suplier;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class EditSup extends javax.swing.JDialog {
private util.Db d;
private entity.Suplier s;
    /**
     * Creates new form EditSup
     */
    public EditSup(java.awt.Frame parent, boolean modal,util.Db db,entity.Suplier ss) {
        super(parent, modal);
        d=db;
        s=ss;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        almt = new javax.swing.JTextArea();
        jns = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tlp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cekal = new javax.swing.JCheckBox();
        si = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nama Perusahaan");

        jLabel2.setText("Alamat");

        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmKeyReleased(evt);
            }
        });

        almt.setColumns(20);
        almt.setRows(5);
        almt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                almtKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(almt);

        jns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jnsKeyReleased(evt);
            }
        });

        jLabel3.setText("Jenis Barang");

        tlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tlpKeyReleased(evt);
            }
        });

        jLabel4.setText("No. Telepon");

        cekal.setText("Dicekal");
        cekal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cekalItemStateChanged(evt);
            }
        });

        si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/sd-card.png"))); // NOI18N
        si.setText("SIMPAN");
        si.setEnabled(false);
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nm)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jns)
                            .addComponent(tlp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cekal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(si, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(cekal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(si)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(rootPane, "Nothing to do!");
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("RALAT DATA SUPLIER : "+s.getId());
        cekal.setSelected(s.isBlocked());
        almt.setText(s.getAlmt());
        jns.setText(s.getJns());
        nm.setText(s.getNm());
        tlp.setText(s.getTlp());
    }//GEN-LAST:event_formWindowOpened

    private void cekalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cekalItemStateChanged
        refresh();
    }//GEN-LAST:event_cekalItemStateChanged

    private void nmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyReleased
        refresh();
    }//GEN-LAST:event_nmKeyReleased

    private void almtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_almtKeyReleased
        refresh();
    }//GEN-LAST:event_almtKeyReleased

    private void jnsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnsKeyReleased
        refresh();
    }//GEN-LAST:event_jnsKeyReleased

    private void tlpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlpKeyReleased
        refresh();
    }//GEN-LAST:event_tlpKeyReleased

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
    try {
        entity.Suplier b=new entity.Suplier(s.getId(), d);
        b.setAlmt(almt.getText());
        b.setBlocked(cekal.isSelected());
        b.setJns(jns.getText());
        b.setNm(nm.getText());
        b.setTlp(tlp.getText());
        new entity.dao.DAOSuplier(d).update(s, b);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        util.Db.hindar(ex);
    }this.setVisible(false);
    }//GEN-LAST:event_siActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt;
    private javax.swing.JCheckBox cekal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jns;
    private javax.swing.JTextField nm;
    private javax.swing.JButton si;
    private javax.swing.JTextField tlp;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        si.setEnabled(!almt.getText().isEmpty()&&!jns.getText().isEmpty()&&!nm.getText().isEmpty()&&!tlp.getText().isEmpty());
    }
}
