/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.operation.jual;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JFrame {
private util.Db d;
private entity.Jual j;
    /**
     * Creates new form Add
     */
    public Add(util.Db db,entity.Jual ju) {
        d=db;
        j=ju;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode = new javax.swing.JLabel();
        f = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Penjualan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kode.setText("jLabel1");

        f.setText("FINISH");
        f.setEnabled(false);
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(f)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        hapusTrans();
        new ui.Dash(d).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        setBarang();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        util.Db.hindar(ex);
    }kode.setText("Nota : "+j.getNota());
    }//GEN-LAST:event_formWindowOpened

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int n=0;
        for(int x=0;x<tbl.getRowCount();x++){
            Boolean b=(Boolean) tbl.getValueAt(x, 0);
            if(b)n++;
        }f.setEnabled(0<n);
    }//GEN-LAST:event_tblMouseClicked

    private void tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyReleased
        this.tblMouseClicked(null);
    }//GEN-LAST:event_tblKeyReleased

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        java.util.ArrayList<entity.DetJual>ad=new java.util.ArrayList<entity.DetJual>();
        for(int x=0;x<tbl.getRowCount();x++){
            Boolean b=(Boolean) tbl.getValueAt(x, 0);
            if(b)try {
                entity.Barang B=new entity.Barang(""+tbl.getValueAt(x, 2), d);
                ad.add(new entity.DetJual(j.getNota(), B.getKode(), Integer.parseInt(""+tbl.getValueAt(x, 1)),
                        B.getHrg().multipliedBy(Integer.parseInt(""+tbl.getValueAt(x, 1)))));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                util.Db.hindar(ex);
            }
        }new ui.operation.jual.AddNext(d, j, ad).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton f;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kode;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void setBarang() throws SQLException {
        javax.swing.table.DefaultTableModel m=new javax.swing.table.DefaultTableModel(new String[]{"Pilih?","JUMLAH","KODE","MERK","HARGA"}, 0){
            private Class[]c=new Class[]{Boolean.class,Integer.class,String.class,String.class,org.joda.money.Money.class};

            @Override
            public boolean isCellEditable(int row, int column) {
                if(column==0)return true;
                if(column==1){
                    Boolean b=(Boolean) this.getValueAt(row, 0);
                    return b;
                }return false;
            }

            @Override
            public Class<?> getColumnClass(int x) {
                return c[x];
            }
        };tbl.setModel(m);
        for(entity.Barang b:new entity.dao.DAOBarang(d).getDatae())
            if(0<b.getStok())m.addRow(new Object[]{false,1,b.getKode(),b.getNm(),b.getHrg()});
    }

    private void hapusTrans() {
    try {
        java.sql.PreparedStatement ps=d.getPS("delete from jual where nota=?");
        ps.setString(1, j.getNota());
        ps.execute();
        ps.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        util.Db.hindar(ex);
    }
    }
}
