/*
 * To change this li            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }ense header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import org.joda.money.CurrencyUnit;

/**
 *
 * @author ai
 */
public class Dash extends javax.swing.JFrame {
public util.Db d;
private entity.Barang sb;
private entity.Suplier ss;
private entity.Pelanggan sp;
private entity.Jual sj;
    /**
     * Creates new form Dash
     */
    public Dash(util.Db db) {
        d=db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        pb2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        btnMemasok = new javax.swing.JButton();
        hb = new javax.swing.JButton();
        eb = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        hs = new javax.swing.JButton();
        rds = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        pb1 = new javax.swing.JButton();
        ldPenj = new javax.swing.JButton();
        hp = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        jButton6 = new javax.swing.JButton();
        rp = new javax.swing.JButton();
        up = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSuplier = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tglJual = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblJual = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tglMemasok = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMemasok = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikonwin.png")).getImage());
        setIconImages(getIconImages());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/power.png"))); // NOI18N
        jButton1.setToolTipText("MENUTUP APLIKASI");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        pb2.setText("PENJUALAN BARU");
        pb2.setEnabled(false);
        pb2.setFocusable(false);
        pb2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pb2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb2ActionPerformed(evt);
            }
        });
        jToolBar1.add(pb2);

        jButton4.setText("STATISTIK PENJUALAN");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setText("Tempat Sampah");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jTabbedPane1.addTab("HOME", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-home-tab.png")), jToolBar1);

        jToolBar2.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/plus.png"))); // NOI18N
        jButton3.setToolTipText("Mendata Barang Baru");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        btnMemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/truck-4.png"))); // NOI18N
        btnMemasok.setToolTipText("MENDATA BARANG MASUK");
        btnMemasok.setFocusable(false);
        btnMemasok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMemasok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemasokActionPerformed(evt);
            }
        });
        jToolBar2.add(btnMemasok);

        hb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/sampah.png"))); // NOI18N
        hb.setToolTipText("Hapus Data Barang Ini");
        hb.setEnabled(false);
        hb.setFocusable(false);
        hb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbActionPerformed(evt);
            }
        });
        jToolBar2.add(hb);

        eb.setText("Edit Barang");
        eb.setEnabled(false);
        eb.setFocusable(false);
        eb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebActionPerformed(evt);
            }
        });
        jToolBar2.add(eb);

        jTabbedPane1.addTab("BARANG", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-barang-tab.png")), jToolBar2); // NOI18N

        jToolBar3.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/add-user-button_1.png"))); // NOI18N
        jButton2.setToolTipText("TAMBAH PEMASOK");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton2);

        hs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/backspace-arrow.png"))); // NOI18N
        hs.setToolTipText("HAPUS PEMASOK");
        hs.setEnabled(false);
        hs.setFocusable(false);
        hs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsActionPerformed(evt);
            }
        });
        jToolBar3.add(hs);

        rds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/create-new-pencil-button.png"))); // NOI18N
        rds.setToolTipText("RALAT DATA PEMASOK");
        rds.setEnabled(false);
        rds.setFocusable(false);
        rds.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rds.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdsActionPerformed(evt);
            }
        });
        jToolBar3.add(rds);

        jTabbedPane1.addTab("SUPLIER", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-supplier-tab.png")), jToolBar3); // NOI18N

        jToolBar4.setRollover(true);

        pb1.setText("PENJUALAN BARU");
        pb1.setEnabled(false);
        pb1.setFocusable(false);
        pb1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pb1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb1ActionPerformed(evt);
            }
        });
        jToolBar4.add(pb1);

        ldPenj.setText("LIHAT DETAIL");
        ldPenj.setEnabled(false);
        ldPenj.setFocusable(false);
        ldPenj.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ldPenj.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ldPenj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldPenjActionPerformed(evt);
            }
        });
        jToolBar4.add(ldPenj);

        hp.setText("Hapus Penjualan");
        hp.setEnabled(false);
        hp.setFocusable(false);
        hp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(hp);

        jTabbedPane1.addTab("PENJUALAN", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-penjualan-tab.png")), jToolBar4); // NOI18N

        jToolBar5.setRollover(true);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/add-user-button_1.png"))); // NOI18N
        jButton6.setToolTipText("Tambah Pelanggan");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar5.add(jButton6);

        rp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/cancel-button.png"))); // NOI18N
        rp.setToolTipText("Hapus Pelanggan");
        rp.setEnabled(false);
        rp.setFocusable(false);
        rp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpActionPerformed(evt);
            }
        });
        jToolBar5.add(rp);

        up.setText("Ubah Data Pelanggan");
        up.setEnabled(false);
        up.setFocusable(false);
        up.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        up.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jToolBar5.add(up);

        jTabbedPane1.addTab("PELANGGAN", new javax.swing.ImageIcon(getClass().getResource("/wijaya/pelanggan.png")), jToolBar5); // NOI18N

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE", "NAMA", "HARGA", "STOK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblBarangMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jTabbedPane2.addTab("BARANG", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-barang-tab.png")), jScrollPane1);

        tblSuplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAMA", "ALAMAT", "JENIS", "DICEKAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSuplier);

        jTabbedPane2.addTab("SUPLIER", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-supplier-tab.png")), jScrollPane2);

        jLabel1.setText("Tanggal");

        tglJual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglJualItemStateChanged(evt);
            }
        });

        tblJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOTA", "TOTAL", "PELANGGAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJualMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblJual);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tglJual, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tglJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("PENJUALAN", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-penjualan-tab.png")), jPanel1);

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE", "NAMA", "ALAMAT", "TELEPON", "CEKAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPelanggan);

        jTabbedPane2.addTab("PELANGGAN", new javax.swing.ImageIcon(getClass().getResource("/wijaya/ikon-pelanggan-tab.png")), jScrollPane4);

        jLabel2.setText("Tanggal :");

        tglMemasok.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglMemasokItemStateChanged(evt);
            }
        });

        tblMemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BARANG", "SUPLIER", "HARGA SATUAN", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblMemasok);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tglMemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tglMemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("PASOKAN BARANG", new javax.swing.ImageIcon(getClass().getResource("/wijaya/list.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        d.close();
        System.exit(0);
    } catch (SQLException ex) {
        util.Db.hindar(ex);
        System.exit(0);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseEntered
    try {
        for(entity.Barang b:new entity.dao.DAOBarang(d).getDatae())
            if(5>b.getStok())JOptionPane.showMessageDialog(rootPane, "Barang "+b.getKode()+" tinggal sedikit. Mohon untuk disuplay.");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_tblBarangMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(isVisible())try {
                    refresh();
                    } catch (InterruptedException | SQLException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                        util.Db.hindar(ex);
                    }
            }
        }).start();sb=null;
    }//GEN-LAST:event_formWindowOpened

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        int s=tblBarang.getSelectedRow();
        boolean b=tblBarang.isRowSelected(s);
        if(b)try {
            sb=new entity.Barang(""+tblBarang.getValueAt(s, 0), d);
            hb.setEnabled(b);
            eb.setEnabled(b);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_tblBarangMouseClicked

    private void tglJualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglJualItemStateChanged
        if(null!=tglJual.getItemAt(tglJual.getSelectedIndex()))try {
            jualTbl();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_tglJualItemStateChanged

    private void tblJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJualMouseClicked
        int s=tblJual.getSelectedRow();
        boolean b=tblJual.isRowSelected(s);
        if(b)try {
            sj=new entity.Jual(""+tblJual.getValueAt(s, 0), d);
            ldPenj.setEnabled(b);
            hp.setEnabled(b);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_tblJualMouseClicked

    private void pb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb2ActionPerformed
    try {
        int i=getTransNow();
        if(sp.isBlocked()){
            int c=javax.swing.JOptionPane.YES_NO_OPTION;
            int x=javax.swing.JOptionPane.showConfirmDialog(rootPane, "Pelanggan ini dicekal. Ingin lanjut?", "LANJUT", c);
            if(x==javax.swing.JOptionPane.NO_OPTION)return;
        }entity.Jual j=new entity.Jual(sp.getKode(), i);
        new entity.dao.DAOJual(d).insert(j);
        new ui.dial.jual.Add(this, rootPaneCheckingEnabled, d, j).setVisible(true);
        jual();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_pb2ActionPerformed

    private void pb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb1ActionPerformed
        this.pb2ActionPerformed(evt);
    }//GEN-LAST:event_pb1ActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        int s=tblPelanggan.getSelectedRow();
        boolean b=tblPelanggan.isRowSelected(s);
        if(b)try {
            sp=new entity.Pelanggan(""+tblPelanggan.getValueAt(s, 0), d);
            pb1.setEnabled(b);
            pb2.setEnabled(b);
            rp.setEnabled(b);
            up.setEnabled(b);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ui.dial.suplier.TambahSup(this, rootPaneCheckingEnabled, d).setVisible(true);try {
        suplier();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new ui.dial.barang.Tambah(this, rootPaneCheckingEnabled, d).setVisible(true);try {
        barang();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ldPenjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldPenjActionPerformed
    try {
        java.util.Map<String,Object>m=new java.util.HashMap<String,Object>();
        m.put("nota", sj.getNota());
        new util.Laporan(this, true, JasperFillManager.fillReport(JasperCompileManager.compileReport(util.Struk.f.getAbsolutePath()),
                m, d.getC())).setVisible(true);
        ldPenj.setEnabled(false);
    } catch (JRException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_ldPenjActionPerformed

    private void tblSuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuplierMouseClicked
        int s=tblSuplier.getSelectedRow();
        boolean b=tblSuplier.isRowSelected(s);
        if(b)try {
            ss=new entity.Suplier(""+tblSuplier.getValueAt(s, 0), d);
            hs.setEnabled(b);
            rds.setEnabled(b);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_tblSuplierMouseClicked

    private void btnMemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemasokActionPerformed
        new ui.dial.barang.Suplied(this, rootPaneCheckingEnabled, d).setVisible(true);try {
            if(null!=tglMemasok.getSelectedItem())memasok();
            barang();
        } catch (SQLException ex) {
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_btnMemasokActionPerformed

    private void hsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsActionPerformed
        int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus data suplier ini?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION)try {
            new entity.dao.DAOSuplier(d).delete(ss);
            suplier();
        } catch (SQLException ex) {
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_hsActionPerformed

    private void rdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdsActionPerformed
    new ui.dial.suplier.EditSup(this, rootPaneCheckingEnabled, d, ss).setVisible(true);try {
        suplier();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_rdsActionPerformed

    private void tglMemasokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglMemasokItemStateChanged
        if(null!=tglMemasok.getSelectedItem())try {
            memasok();
        } catch (SQLException ex) {
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_tglMemasokItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new ui.Analyze(this, true, d).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    try {
        d.close();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_formWindowClosing

    private void hbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbActionPerformed
        int c=javax.swing.JOptionPane.YES_NO_OPTION;
        int x=javax.swing.JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus barang ini?", "Hapus?", c);
        if(x==javax.swing.JOptionPane.YES_OPTION)try {
            new entity.dao.DAOBarang(d).delete(sb);
            barang();
        } catch (SQLException ex) {
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_hbActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new ui.Trash(this, true, d).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new ui.dial.pelanggan.Add(this, true, d).setVisible(true);try {
        pelanggan();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void rpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpActionPerformed
        int c=javax.swing.JOptionPane.YES_NO_OPTION;
        int s=javax.swing.JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus akun ini?", "HAPUS?", c);
        if(s==javax.swing.JOptionPane.YES_OPTION)try {
            new entity.dao.DAOPelanggan(d).delete(sp);
            pelanggan();
        } catch (SQLException ex) {
            util.Db.hindar(ex);
        }
    }//GEN-LAST:event_rpActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
    new ui.dial.pelanggan.Edit(this, true, d, sp).setVisible(true);try {
        pelanggan();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_upActionPerformed

    private void ebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebActionPerformed
        new ui.dial.barang.Edit(this, true, sb, d).setVisible(true);try {
        barang();
    } catch (SQLException ex) {
        util.Db.hindar(ex);
    }
    }//GEN-LAST:event_ebActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMemasok;
    private javax.swing.JButton eb;
    private javax.swing.JButton hb;
    private javax.swing.JButton hp;
    private javax.swing.JButton hs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JButton ldPenj;
    private javax.swing.JButton pb1;
    private javax.swing.JButton pb2;
    private javax.swing.JButton rds;
    private javax.swing.JButton rp;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblJual;
    private javax.swing.JTable tblMemasok;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTable tblSuplier;
    private javax.swing.JComboBox<String> tglJual;
    private javax.swing.JComboBox<java.sql.Date> tglMemasok;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables

    private void refresh() throws InterruptedException, SQLException {
        barang();
        suplier();
        jual();
        if(null!=tglJual.getItemAt(tglJual.getSelectedIndex()))jualTbl();
        pelanggan();
        initMemasok();
        if(null!=tglMemasok.getSelectedItem())memasok();
        Thread.sleep(10000);
    }

    private void barang() throws SQLException {
        javax.swing.table.DefaultTableModel m=(javax.swing.table.DefaultTableModel) tblBarang.getModel();
        for(int x=m.getRowCount()-1;x>=0;x--)m.removeRow(x);
        for(entity.Barang b:new entity.dao.DAOBarang(d).getDatae())
            m.addRow(new Object[]{b.getKode(),b.getNm(),b.getHrg(),""+b.getStok()+" "+b.getSatuan()});
    }

    private void suplier() throws SQLException {
        javax.swing.table.DefaultTableModel m=(javax.swing.table.DefaultTableModel) tblSuplier.getModel();
        for(int x=m.getRowCount()-1;x>=0;x--)m.removeRow(x);
        for(entity.Suplier s:new entity.dao.DAOSuplier(d).getDatae())
            m.addRow(new Object[]{s.getId(),s.getNm(),s.getAlmt(),s.getJns(),s.isBlocked()});
    }

    private void jual() throws SQLException {
        tglJual.removeAllItems();
        java.sql.ResultSet rs=d.keluar("select distinct tgl from jual");
        while(rs.next())tglJual.addItem(rs.getString("tgl"));
        rs.close();
        javax.swing.table.DefaultTableModel m=(javax.swing.table.DefaultTableModel) tblJual.getModel();
        for(int x=m.getRowCount()-1;x>=0;x--)m.removeRow(x);
    }

    private void jualTbl() throws SQLException {
        javax.swing.table.DefaultTableModel m=(javax.swing.table.DefaultTableModel) tblJual.getModel();
        for(int x=m.getRowCount()-1;x>=0;x--)m.removeRow(x);
        java.sql.PreparedStatement ps=d.getPS("select nota,total,pel from jual where tgl=?");
        ps.setDate(1, java.sql.Date.valueOf(tglJual.getItemAt(tglJual.getSelectedIndex())));
        java.sql.ResultSet rs=ps.executeQuery();
        while(rs.next()){
            entity.Pelanggan p=new entity.Pelanggan(rs.getString("pel"), d);
            m.addRow(new Object[]{rs.getString("nota"),rs.getString("total"),p.getNm()});
        }rs.close();
        ps.close();
    }

    private void pelanggan() throws SQLException {
        javax.swing.table.DefaultTableModel m=(javax.swing.table.DefaultTableModel) tblPelanggan.getModel();
        for(int x=m.getRowCount()-1;x>=0;x--)m.removeRow(x);
        for(entity.Pelanggan p:new entity.dao.DAOPelanggan(d).getDatae())
            m.addRow(new Object[]{p.getKode(),p.getNm(),p.getAlmt(),p.getTlp(),p.isBlocked()});
    }

    private int getTransNow() throws SQLException {
        int i=0;
        java.sql.PreparedStatement ps=d.getPS("select count(nota)as jum from jual where tgl=?");
        ps.setDate(1, java.sql.Date.valueOf(LocalDate.now()));
        java.sql.ResultSet rs=ps.executeQuery();
        if(rs.next())i=1+rs.getInt("jum");
        rs.close();
        ps.close();
        return i;
    }

    private void memasok() throws SQLException {
        java.sql.PreparedStatement ps=d.getPS("select*from memasok where tgl=?");
        ps.setDate(1, tglMemasok.getItemAt(tglMemasok.getSelectedIndex()));
        java.sql.ResultSet rs=ps.executeQuery();
        javax.swing.table.DefaultTableModel m=(javax.swing.table.DefaultTableModel) tblMemasok.getModel();
        for(int x=m.getRowCount()-1;x>=0;x--)m.removeRow(x);
        while(rs.next())
            m.addRow(new Object[]{rs.getString("brg"),rs.getString("sup"),org.joda.money.Money.of(CurrencyUnit.of("IDR"), rs.getLong("sat")),
            rs.getFloat("jum")});
        rs.close();
        ps.close();
    }

    private void initMemasok() throws SQLException {
        tglMemasok.removeAllItems();
        java.sql.ResultSet rs=d.keluar("select distinct tgl from memasok");
        while(rs.next())tglMemasok.addItem(rs.getDate("tgl"));
        rs.close();
    }
}
