/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.dial.jual;

import org.joda.money.CurrencyUnit;

/**
 *
 * @author ai
 */
public class BrgItem extends javax.swing.JInternalFrame {
private entity.Barang b;
private String nota;
    /**
     * Creates new form BrgItem
     */
    public BrgItem(entity.Barang brg,String s) {
        b=brg;
        nota=s;
        initComponents();
        muat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nm = new javax.swing.JLabel();
        min = new javax.swing.JButton();
        jum = new javax.swing.JTextField();
        plus = new javax.swing.JButton();
        satuan = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/wijaya/shopping-cart.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(378, 108));

        nm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nm.setText("???");

        min.setText("-");
        min.setEnabled(false);
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });

        jum.setEditable(false);
        jum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jum.setText("0");

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        satuan.setText("???");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jum, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(satuan, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min)
                    .addComponent(jum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus)
                    .addComponent(satuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        float f=Float.parseFloat(jum.getText());
        f-=1;
        min.setEnabled(f>0);
        plus.setEnabled(f<b.getStok());
        jum.setText(""+f);
    }//GEN-LAST:event_minActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        float f=Float.parseFloat(jum.getText());
        f+=1;
        min.setEnabled(f>0);
        plus.setEnabled(f<b.getStok());
        jum.setText(""+f);
    }//GEN-LAST:event_plusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jum;
    private javax.swing.JButton min;
    private javax.swing.JLabel nm;
    private javax.swing.JButton plus;
    private javax.swing.JLabel satuan;
    // End of variables declaration//GEN-END:variables

    private void muat() {
        nm.setText(b.getNm());
        this.setTitle(b.getKode()+" ("+b.getHrg()+"/"+b.getSatuan()+")");
        satuan.setText(b.getSatuan());
        this.setVisible(true);
    }

    public entity.DetJual getDJ(){
        if(0<Float.parseFloat(jum.getText())){
            double d=b.getHrg().getAmount().doubleValue()*Float.parseFloat(jum.getText());
            org.joda.money.Money byr=org.joda.money.Money.of(CurrencyUnit.of("IDR"), d);
            return new entity.DetJual(nota, b.getKode(), (float) d, byr);
        }return null;
    }
}